name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:24
    defaults:
      run:
        working-directory: ./project-tea
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.PUBLISHER_KEY }}